; Kanto hack: Yellow's CENTER REST HOUSE (docs/M7-FUCHSIA.md 10m).  All four
; SAFARI ZONE rest houses are the same 4x4 room in Yellow and their four .blk
; files are byte-identical, so per D67 the four maps share ONE INCBIN --
; maps/SafariZoneRestHouse.blk, generated by scripts/kanto_gate_blk.py from
; vendor/pokeyellow/maps/SafariZoneCenterRestHouse.blk with only block $00
; rewritten to its $7f twin.  The NPCs and their lines differ per house and are
; Yellow's verbatim (vendor/pokeyellow/{data/maps/objects,text}/*RestHouse.asm).
; Yellow's SPRITE_GIRL has no Crystal counterpart; SPRITE_LASS is the standing
; substitution used everywhere else in this hack.
	object_const_def
	const SAFARIZONECENTERRESTHOUSE_LASS
	const SAFARIZONECENTERRESTHOUSE_SCIENTIST

SafariZoneCenterRestHouse_MapScripts:
	def_scene_scripts

	def_callbacks

SafariZoneCenterRestHouseLassScript:
	jumptextfaceplayer SafariZoneCenterRestHouseLassText

SafariZoneCenterRestHouseScientistScript:
	jumptextfaceplayer SafariZoneCenterRestHouseScientistText

SafariZoneCenterRestHouseLassText:
	text "SARA: Where did"
	line "my boy friend,"
	cont "ERIK, go?"
	done

SafariZoneCenterRestHouseScientistText:
	text "I'm catching"
	line "#MON to take"
	cont "home as gifts!"
	done

SafariZoneCenterRestHouse_MapEvents:
	db 0, 0 ; filler

	def_warp_events
	warp_event  2,  7, SAFARI_ZONE_CENTER, 9
	warp_event  3,  7, SAFARI_ZONE_CENTER, 9

	def_coord_events

	def_bg_events

	def_object_events
	object_event  3,  2, SPRITE_LASS, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_SCRIPT, 0, SafariZoneCenterRestHouseLassScript, -1
	object_event  1,  4, SPRITE_SCIENTIST, SPRITEMOVEDATA_WALK_UP_DOWN, 0, 1, -1, -1, PAL_NPC_BLUE, OBJECTTYPE_SCRIPT, 0, SafariZoneCenterRestHouseScientistScript, -1
