; TILESET_KANTO_GATE -- generated by scripts/kanto_gate_blk.py from
; Yellow's gate blockset and its Gate_Coll whitelist.  Do not hand-edit:
; `scripts/kanto_gate_blk.py --check` diffs this file against the source.
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 00  ; unusable in GSC -- see scripts/kanto_gate_blk.py
	tilecoll FLOOR, COUNTER, FLOOR, COUNTER ; 01
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 02
	tilecoll WALL, WALL, FLOOR, FLOOR ; 03
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 04
	tilecoll LADDER, FLOOR, FLOOR, FLOOR ; 05  ; warp override
	tilecoll WALL, WALL, WALL, FLOOR ; 06
	tilecoll WALL, WALL, FLOOR, WALL ; 07
	tilecoll FLOOR, COUNTER, FLOOR, COUNTER ; 08
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 09
	tilecoll WALL, WALL, WALL, WALL ; 0a
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 0b  ; warp override
	tilecoll FLOOR, COUNTER, WARP_CARPET_DOWN, FLOOR ; 0c  ; warp override
	tilecoll COUNTER, WALL, FLOOR, WALL ; 0d
	tilecoll WALL, COUNTER, WALL, FLOOR ; 0e
	tilecoll COUNTER, FLOOR, FLOOR, WARP_CARPET_DOWN ; 0f  ; warp override
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 10
	tilecoll FLOOR, COUNTER, FLOOR, COUNTER ; 11
	tilecoll FLOOR, FLOOR, COUNTER, FLOOR ; 12
	tilecoll FLOOR, FLOOR, FLOOR, COUNTER ; 13
	tilecoll FLOOR, COUNTER, FLOOR, FLOOR ; 14
	tilecoll COUNTER, FLOOR, FLOOR, FLOOR ; 15
	tilecoll COUNTER, WALL, COUNTER, WALL ; 16
	tilecoll WALL, COUNTER, WALL, COUNTER ; 17
	tilecoll COUNTER, FLOOR, COUNTER, COUNTER ; 18
	tilecoll FLOOR, COUNTER, COUNTER, COUNTER ; 19
	tilecoll COUNTER, FLOOR, FLOOR, FLOOR ; 1a
	tilecoll FLOOR, COUNTER, FLOOR, FLOOR ; 1b
	tilecoll COUNTER, COUNTER, COUNTER, FLOOR ; 1c
	tilecoll COUNTER, COUNTER, FLOOR, COUNTER ; 1d
	tilecoll FLOOR, FLOOR, COUNTER, COUNTER ; 1e
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 1f
	tilecoll FLOOR, COUNTER, FLOOR, FLOOR ; 20
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 21
	tilecoll COUNTER, FLOOR, FLOOR, FLOOR ; 22
	tilecoll LADDER, COUNTER, COUNTER, COUNTER ; 23  ; warp override
	tilecoll FLOOR, FLOOR, FLOOR, COUNTER ; 24
	tilecoll FLOOR, FLOOR, COUNTER, COUNTER ; 25
	tilecoll FLOOR, FLOOR, COUNTER, FLOOR ; 26
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 27
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 28
	tilecoll FLOOR, FLOOR, COUNTER, COUNTER ; 29
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 2a
	tilecoll FLOOR, COUNTER, FLOOR, COUNTER ; 2b
	tilecoll FLOOR, WALL, FLOOR, COUNTER ; 2c
	tilecoll WALL, FLOOR, COUNTER, FLOOR ; 2d
	tilecoll WALL, WALL, FLOOR, COUNTER ; 2e
	tilecoll WALL, WALL, COUNTER, FLOOR ; 2f
	tilecoll COUNTER, FLOOR, COUNTER, COUNTER ; 30
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 31
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 32
	tilecoll WALL, WALL, WALL, WALL ; 33
	tilecoll WALL, WALL, WALL, WALL ; 34
	tilecoll WALL, WALL, WALL, WALL ; 35
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 36
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 37
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 38
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 39  ; warp override
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3b
	tilecoll WALL, WALL, FLOOR, FLOOR ; 3c
	tilecoll WALL, WALL, WALL, WALL ; 3d
	tilecoll WALL, WALL, WALL, FLOOR ; 3e
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 3f
	tilecoll FLOOR, WALL, FLOOR, COUNTER ; 40
	tilecoll WALL, WALL, COUNTER, COUNTER ; 41
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 42
	tilecoll WALL, WALL, FLOOR, COUNTER ; 43
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 44
	tilecoll FLOOR, FLOOR, WALL, WALL ; 45
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 46
	tilecoll FLOOR, FLOOR, COUNTER, FLOOR ; 47
	tilecoll FLOOR, COUNTER, FLOOR, FLOOR ; 48
	tilecoll COUNTER, COUNTER, FLOOR, FLOOR ; 49
	tilecoll FLOOR, COUNTER, FLOOR, COUNTER ; 4a
	tilecoll COUNTER, FLOOR, FLOOR, FLOOR ; 4b
	tilecoll FLOOR, COUNTER, FLOOR, COUNTER ; 4c
	tilecoll WALL, WALL, WALL, WALL ; 4d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4e
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 4f
	tilecoll WALL, WALL, FLOOR, FLOOR ; 50
	tilecoll FLOOR, FLOOR, COUNTER, COUNTER ; 51
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 52  ; warp override
	tilecoll WALL, FLOOR, COUNTER, FLOOR ; 53
	tilecoll FLOOR, FLOOR, COUNTER, COUNTER ; 54
	tilecoll FLOOR, FLOOR, COUNTER, COUNTER ; 55
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 56  ; warp override
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 57
	tilecoll FLOOR, WALL, FLOOR, COUNTER ; 58
	tilecoll WALL, WALL, COUNTER, COUNTER ; 59
	tilecoll WALL, FLOOR, COUNTER, FLOOR ; 5a
	tilecoll COUNTER, FLOOR, FLOOR, FLOOR ; 5b
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5f
	tilecoll FLOOR, FLOOR, COUNTER, FLOOR ; 60
	tilecoll COUNTER, FLOOR, FLOOR, FLOOR ; 61
	tilecoll COUNTER, FLOOR, COUNTER, FLOOR ; 62
	tilecoll COUNTER, WALL, COUNTER, WALL ; 63
	tilecoll FLOOR, WALL, COUNTER, WALL ; 64
	tilecoll COUNTER, WALL, FLOOR, WALL ; 65
	tilecoll WARP_CARPET_LEFT, FLOOR, WARP_CARPET_LEFT, FLOOR ; 66  ; warp override
	tilecoll FLOOR, WARP_CARPET_RIGHT, FLOOR, WARP_CARPET_RIGHT ; 67  ; warp override
	tilecoll WALL, WALL, COUNTER, COUNTER ; 68
	tilecoll FLOOR, COUNTER, WARP_CARPET_DOWN, FLOOR ; 69  ; warp override
	tilecoll DOOR, FLOOR, FLOOR, COUNTER ; 6a  ; warp override
	tilecoll FLOOR, DOOR, COUNTER, FLOOR ; 6b  ; warp override
	tilecoll COUNTER, FLOOR, FLOOR, WARP_CARPET_DOWN ; 6c  ; warp override
	tilecoll FLOOR, WARP_CARPET_RIGHT, COUNTER, FLOOR ; 6d  ; warp override
	tilecoll WARP_CARPET_LEFT, FLOOR, FLOOR, COUNTER ; 6e  ; warp override
	tilecoll COUNTER, FLOOR, FLOOR, WARP_CARPET_RIGHT ; 6f  ; warp override
	tilecoll FLOOR, COUNTER, WARP_CARPET_LEFT, FLOOR ; 70  ; warp override
	tilecoll DOOR, DOOR, FLOOR, FLOOR ; 71  ; warp override
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 72  ; warp override
	tilecoll WALL, DOOR, FLOOR, FLOOR ; 73  ; warp override
	tilecoll FLOOR, WALL, FLOOR, WALL ; 74
	tilecoll WALL, WALL, WALL, WALL ; 75
	tilecoll WALL, WALL, WALL, WALL ; 76
	tilecoll WALL, WALL, WALL, WALL ; 77
	tilecoll WALL, WALL, WALL, WALL ; 78
	tilecoll WALL, WALL, WALL, WALL ; 79
	tilecoll WALL, WALL, WALL, WALL ; 7a
	tilecoll WALL, WALL, WALL, WALL ; 7b
	tilecoll WALL, WALL, WALL, WALL ; 7c
	tilecoll WALL, WALL, WALL, WALL ; 7d
	tilecoll WALL, WALL, WALL, WALL ; 7e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 7f  ; twin of block $00, which GSC cannot use
