; TILESET_KANTO_CAVE -- generated by scripts/ct1_kanto_cave.py from Yellow's
; cavern blockset, its Cavern_Coll whitelist, and the per-cell collision the
; pre-CT1 ports shipped (pyrite 4089122).  Do not hand-edit: `--check` diffs it.
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll WALL, FLOOR, WALL, WALL ; 02
	tilecoll WALL, WALL, WALL, WALL ; 03
	tilecoll FLOOR, FLOOR, WALL, WALL ; 04
	tilecoll WALL, WALL, FLOOR, FLOOR ; 05
	tilecoll WALL, FLOOR, WALL, FLOOR ; 06
	tilecoll FLOOR, WALL, FLOOR, WALL ; 07
	tilecoll WALL, WALL, WALL, FLOOR ; 08
	tilecoll WALL, WALL, FLOOR, WALL ; 09
	tilecoll WALL, FLOOR, WALL, WALL ; 0a
	tilecoll FLOOR, WALL, WALL, WALL ; 0b
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 0c
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 0d
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 10
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 11
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 12
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 13
	tilecoll WALL, FLOOR, WALL, FLOOR ; 14
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 15
	tilecoll FLOOR, WALL, FLOOR, WALL ; 16
	tilecoll WALL, FLOOR, WALL, FLOOR ; 17
	tilecoll WALL, FLOOR, WALL, FLOOR ; 18
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 19
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1b
	tilecoll WALL, FLOOR, WALL, WALL ; 1c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 1d
	tilecoll FLOOR, WALL, WALL, WALL ; 1e
	tilecoll WALL, FLOOR, WALL, WALL ; 1f
	tilecoll WALL, FLOOR, WALL, WALL ; 20
	tilecoll FLOOR, FLOOR, WALL, WALL ; 21
	tilecoll FLOOR, FLOOR, WALL, WALL ; 22
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 23
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 24
	tilecoll FLOOR, WALL, WALL, WALL ; 25
	tilecoll WALL, FLOOR, WALL, FLOOR ; 26
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 27
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 28
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 29
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 2a
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 2b
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 2c
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll WALL, WALL, WALL, WALL ; 2f
	tilecoll FLOOR, WALL, FLOOR, WALL ; 30
	tilecoll WALL, WALL, FLOOR, FLOOR ; 31
	tilecoll WALL, FLOOR, WALL, FLOOR ; 32
	tilecoll FLOOR, FLOOR, WALL, WALL ; 33
	tilecoll WALL, FLOOR, WALL, WALL ; 34
	tilecoll FLOOR, WALL, WALL, WALL ; 35
	tilecoll WALL, FLOOR, WALL, FLOOR ; 36
	tilecoll FLOOR, WALL, FLOOR, WALL ; 37
	tilecoll WALL, WALL, WALL, WALL ; 38
	tilecoll WALL, WALL, FLOOR, FLOOR ; 39
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3a
	tilecoll FLOOR, WALL, FLOOR, WALL ; 3b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
	tilecoll WALL, WALL, WALL, FLOOR ; 40
	tilecoll WALL, WALL, FLOOR, FLOOR ; 41
	tilecoll WALL, WALL, FLOOR, WALL ; 42
	tilecoll WALL, WALL, WALL, WALL ; 43
	tilecoll FLOOR, FLOOR, WALL, WALL ; 44
	tilecoll FLOOR, FLOOR, WALL, WALL ; 45
	tilecoll WALL, WALL, FLOOR, WALL ; 46
	tilecoll FLOOR, FLOOR, WALL, WALL ; 47
	tilecoll WALL, FLOOR, WALL, FLOOR ; 48
	tilecoll FLOOR, WALL, FLOOR, WALL ; 49
	tilecoll WALL, FLOOR, WALL, WALL ; 4a
	tilecoll FLOOR, WALL, WALL, WALL ; 4b
	tilecoll WALL, FLOOR, WALL, WALL ; 4c
	tilecoll WALL, WALL, WALL, WALL ; 4d
	tilecoll WALL, WALL, WALL, WALL ; 4e
	tilecoll WALL, WALL, WALL, FLOOR ; 4f
	tilecoll FLOOR, FLOOR, WALL, WALL ; 50
	tilecoll WALL, WALL, WALL, WALL ; 51
	tilecoll WALL, WALL, WALL, WALL ; 52
	tilecoll WALL, WALL, WALL, WALL ; 53
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 54
	tilecoll WALL, WALL, FLOOR, FLOOR ; 55
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 56
	tilecoll WALL, WALL, WALL, FLOOR ; 57
	tilecoll WALL, WALL, WALL, WALL ; 58
	tilecoll FLOOR, WALL, WALL, WALL ; 59
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 5a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5c
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 5d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 5e
	tilecoll WALL, WALL, WALL, WALL ; 5f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 60
	tilecoll FLOOR, FLOOR, WALL, WALL ; 61
	tilecoll WALL, WALL, WALL, FLOOR ; 62
	tilecoll WALL, WALL, FLOOR, FLOOR ; 63
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 64
	tilecoll WALL, FLOOR, WALL, WALL ; 65
	tilecoll WALL, FLOOR, WALL, FLOOR ; 66
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 67
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 68
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 69
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 6a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 6b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 6c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 6d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 6e
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 6f
	tilecoll WALL, WALL, WALL, WALL ; 70
	tilecoll WALL, WALL, WALL, WALL ; 71
	tilecoll WALL, WALL, WALL, WALL ; 72
	tilecoll WALL, FLOOR, WALL, FLOOR ; 73
	tilecoll WALL, WALL, WALL, WALL ; 74
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 75
	tilecoll WATER, WATER, WATER, WATER ; 76
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 77
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 78
	tilecoll FLOOR, FLOOR, WALL, WALL ; 79
	tilecoll WALL, WALL, FLOOR, WALL ; 7a
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 7b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 7c
	tilecoll WALL, WALL, WALL, WALL ; 7d
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 7e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 7f
; collision clones: Yellow's art byte for byte, other collision
	tilecoll WALL, WALL, WALL, WALL ; 80 = $02 (MtMoon1F, RockTunnel1F, RockTunnelB1F, VictoryRoad3F)
	tilecoll WALL, UP_WALL, WALL, FLOOR ; 81 = $14 (VictoryRoad1F, VictoryRoad2F, VictoryRoad3F)
	tilecoll WALL, WALL, WALL, WALL ; 82 = $14 (MtMoon1F, RockTunnel1F)
	tilecoll UP_WALL, UP_WALL, FLOOR, FLOOR ; 83 = $15 (DiglettsCave, VictoryRoad1F, VictoryRoad2F, VictoryRoad2F switch, VictoryRoad3F)
	tilecoll WALL, WALL, WALL, WALL ; 84 = $15 (MtMoonB2F, RockTunnel1F)
	tilecoll UP_WALL, WALL, FLOOR, WALL ; 85 = $16 (DiglettsCave, VictoryRoad1F, VictoryRoad2F, VictoryRoad3F)
	tilecoll WALL, WALL, WALL, WALL ; 86 = $16 (MtMoon1F, RockTunnel1F)
	tilecoll WALL, WALL, WALL, WALL ; 87 = $17 (MtMoon1F, RockTunnel1F, RockTunnelB1F)
	tilecoll WALL, WALL, WALL, WALL ; 88 = $18 (MtMoon1F, RockTunnel1F)
	tilecoll WALL, WALL, WALL, WALL ; 89 = $19 (MtMoonB2F, RockTunnel1F)
	tilecoll WALL, WALL, WALL, WALL ; 8a = $1a (MtMoon1F, RockTunnel1F)
	tilecoll WALL, WALL, WALL, WALL ; 8b = $1b (MtMoon1F)
	tilecoll WALL, WALL, WALL, WALL ; 8c = $1c (MtMoon1F, RockTunnel1F)
	tilecoll WALL, WALL, WALL, WALL ; 8d = $1d (RockTunnel1F)
	tilecoll WALL, WALL, WALL, WALL ; 8e = $1e (MtMoon1F, RockTunnel1F)
	tilecoll WALL, WALL, WALL, WALL ; 8f = $1f (MtMoon1F, RockTunnel1F, RockTunnelB1F)
	tilecoll WALL, WALL, WALL, WALL ; 90 = $20 (MtMoon1F, RockTunnel1F, RockTunnelB1F)
	tilecoll WALL, WALL, WALL, WALL ; 91 = $21 (MtMoon1F)
	tilecoll WALL, WALL, WALL, WALL ; 92 = $22 (MtMoon1F, RockTunnel1F, RockTunnelB1F)
	tilecoll LADDER, WALL, FLOOR, FLOOR ; 93 = $23 (VictoryRoad2F, VictoryRoad3F)
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 94 = $24 (DiglettsCaveRoute11, DiglettsCaveRoute2, MtMoon1F, SeafoamIslands1F, VictoryRoad1F)
	tilecoll WALL, UP_WALL, WALL, FLOOR ; 95 = $26 (VictoryRoad2F)
	tilecoll LADDER, FLOOR, FLOOR, FLOOR ; 96 = $27 (DiglettsCaveRoute11, DiglettsCaveRoute2, SeafoamIslandsB1F, SeafoamIslandsB3F, VictoryRoad3F)
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 97 = $28 (MtMoon1F, RockTunnel1F, SeafoamIslands1F, SeafoamIslandsB1F, SeafoamIslandsB2F, VictoryRoad3F)
	tilecoll UP_WALL, WALL, FLOOR, WALL ; 98 = $37 (VictoryRoad2F)
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 99 = $3c (MtMoonB1F, SeafoamIslands1F, SeafoamIslandsB1F, SeafoamIslandsB2F)
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 9a = $3d (MtMoonB1F, MtMoonB2F, SeafoamIslandsB2F, SeafoamIslandsB3F)
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 9b = $3e (DiglettsCave, MtMoonB2F, RockTunnel1F, RockTunnelB1F, SeafoamIslandsB1F, SeafoamIslandsB2F, VictoryRoad2F)
	tilecoll FLOOR, FLOOR, UP_WALL, UP_WALL ; 9c = $5b (VictoryRoad1F)
	tilecoll FLOOR, LADDER, WALL, WALL ; 9d = $61 (SeafoamIslandsB3F, SeafoamIslandsB4F, VictoryRoad2F)
	tilecoll WALL, WALL, WALL, LADDER ; 9e = $62 (VictoryRoad1F, VictoryRoad2F)
	tilecoll WALL, WALL, FLOOR, WARP_CARPET_RIGHT ; 9f = $63 (VictoryRoad2F)
	tilecoll FLOOR, WARP_CARPET_RIGHT, FLOOR, WALL ; a0 = $67 (VictoryRoad2F)
	tilecoll FLOOR, FLOOR, FLOOR, PIT ; a1 = $69 (VictoryRoad3F)
	tilecoll FLOOR, FLOOR, WALL, UP_WALL ; a2 = $6a (VictoryRoad1F, VictoryRoad3F)
	tilecoll PIT, FLOOR, FLOOR, FLOOR ; a3 = $77 (SeafoamIslands1F, SeafoamIslandsB1F, SeafoamIslandsB2F, SeafoamIslandsB3F)
	tilecoll FLOOR, PIT, FLOOR, FLOOR ; a4 = $78 (SeafoamIslands1F, SeafoamIslandsB1F, SeafoamIslandsB2F, SeafoamIslandsB3F)
	tilecoll FLOOR, LADDER, WALL, WALL ; a5 = $79 (SeafoamIslandsB2F, SeafoamIslandsB3F)
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; a6 = $7c (SeafoamIslandsB1F, SeafoamIslandsB2F, SeafoamIslandsB4F)
