; Generated by scripts/vermilion_blk.py from Yellow's ship_port.bst
; and ShipPort_Coll whitelist -- see that script's KANTO_DOCK
; section.  Do not edit.
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 00
	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll WALL, WALL, FLOOR, FLOOR ; 03
	tilecoll WALL, WALL, WALL, WALL ; 04
	tilecoll WALL, WALL, WALL, WALL ; 05
	tilecoll LADDER, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll WALL, WALL, WALL, WALL ; 08
	tilecoll WALL, WALL, WALL, WALL ; 09
	tilecoll WALL, WALL, WALL, WALL ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0c
	tilecoll WATER, WATER, WATER, WATER ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 14
	tilecoll LADDER, WALL, FLOOR, WALL ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll FLOOR, WALL, WALL, WALL ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
