; TILESET_KANTO_FACILITY -- generated by scripts/celadon_blk.py from
; Yellow's facility blockset and its Facility_Coll whitelist.  Do not
; hand-edit: `scripts/celadon_blk.py --check` diffs it against the source.
; Warp collisions live in that script's OVERRIDES; the $80+ rows are M6
; 9w's spin-maze repaints of Yellow's own arrow runs (D31/D32).
	tilecoll WALL, WALL, WALL, WALL ; 00  ; unusable in GSC, but no RocketHideout map uses block $00
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 03
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 04
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, FLOOR, FLOOR ; 07
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 08
	tilecoll FLOOR, WALL, FLOOR, WALL ; 09
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll WALL, WALL, WALL, WALL ; 0c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0f
	tilecoll WALL, WALL, WALL, FLOOR ; 10
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, FLOOR, FLOOR ; 13
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 14
	tilecoll FLOOR, WALL, FLOOR, WALL ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll FLOOR, WALL, FLOOR, WALL ; 17
	tilecoll WALL, WALL, WALL, FLOOR ; 18
	tilecoll WALL, WALL, FLOOR, FLOOR ; 19
	tilecoll WALL, WALL, FLOOR, WALL ; 1a
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 1b
	tilecoll WALL, FLOOR, WALL, WALL ; 1c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 1d
	tilecoll FLOOR, WALL, WALL, WALL ; 1e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 1f
	tilecoll FLOOR, WALL, FLOOR, WALL ; 20
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 21
	tilecoll FLOOR, FLOOR, COUNTER, COUNTER ; 22
	tilecoll WALL, FLOOR, COUNTER, FLOOR ; 23
	tilecoll STAIRCASE, WALL, FLOOR, FLOOR ; 24
	tilecoll WALL, FLOOR, WALL, FLOOR ; 25
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 26
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 27
	tilecoll WALL, WALL, WALL, WALL ; 28
	tilecoll FLOOR, FLOOR, WALL, WALL ; 29
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 2a
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 2b
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 2c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll FLOOR, FLOOR, FLOOR, WARP_PANEL ; 2f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 30
	tilecoll FLOOR, WALL, FLOOR, WALL ; 31
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 32
	tilecoll WALL, WALL, WALL, WALL ; 33
	tilecoll FLOOR, FLOOR, WALL, WALL ; 34
	tilecoll WALL, WALL, WALL, WALL ; 35
	tilecoll WALL, WALL, WALL, WALL ; 36
	tilecoll WALL, WALL, FLOOR, FLOOR ; 37
	tilecoll WALL, FLOOR, WALL, FLOOR ; 38
	tilecoll WALL, FLOOR, WALL, FLOOR ; 39
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3b
	tilecoll WALL, WALL, WALL, FLOOR ; 3c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 3d
	tilecoll WALL, WALL, FLOOR, WALL ; 3e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3f
	tilecoll WALL, WALL, WALL, FLOOR ; 40
	tilecoll WALL, WALL, FLOOR, FLOOR ; 41
	tilecoll WALL, WALL, FLOOR, WALL ; 42
	tilecoll WALL, FLOOR, WALL, FLOOR ; 43
	tilecoll WALL, FLOOR, WALL, FLOOR ; 44
	tilecoll FLOOR, WALL, FLOOR, WALL ; 45
	tilecoll FLOOR, WALL, FLOOR, WALL ; 46
	tilecoll WALL, WALL, WALL, WALL ; 47
	tilecoll WALL, FLOOR, WALL, WALL ; 48
	tilecoll FLOOR, FLOOR, WALL, WALL ; 49
	tilecoll FLOOR, WALL, WALL, WALL ; 4a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 4b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 4f
	tilecoll WALL, FLOOR, WALL, WALL ; 50
	tilecoll FLOOR, WALL, WALL, WALL ; 51
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 52
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 53
	tilecoll WALL, WALL, FLOOR, FLOOR ; 54
	tilecoll WALL, FLOOR, WALL, FLOOR ; 55
	tilecoll FLOOR, WALL, FLOOR, WALL ; 56
	tilecoll FLOOR, FLOOR, WALL, WALL ; 57
	tilecoll FLOOR, FLOOR, WALL, WALL ; 58
	tilecoll WALL, FLOOR, WALL, FLOOR ; 59
	tilecoll FLOOR, WALL, FLOOR, WALL ; 5a
	tilecoll WALL, WALL, WALL, WALL ; 5b
	tilecoll WALL, WALL, WALL, WALL ; 5c
	tilecoll WALL, WALL, WALL, WALL ; 5d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 5e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 5f
	tilecoll WALL, WALL, WALL, WALL ; 60
	tilecoll WALL, WALL, WALL, WALL ; 61
	tilecoll WALL, WALL, WALL, WALL ; 62
	tilecoll WALL, WALL, FLOOR, FLOOR ; 63
	tilecoll WALL, WALL, WALL, WALL ; 64
	tilecoll WALL, WALL, WALL, WALL ; 65
	tilecoll WALL, WALL, WALL, WALL ; 66
	tilecoll WALL, WALL, FLOOR, FLOOR ; 67
	tilecoll WALL, WALL, WALL, WALL ; 68
	tilecoll WALL, WALL, WALL, WALL ; 69
	tilecoll WALL, WALL, FLOOR, FLOOR ; 6a
	tilecoll WALL, WALL, WALL, WALL ; 6b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 6c
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 6d
	tilecoll FLOOR, STAIRCASE, FLOOR, FLOOR ; 6e
	tilecoll FLOOR, STAIRCASE, FLOOR, FLOOR ; 6f
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 70
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 71
	tilecoll FLOOR, FLOOR, WALL, WALL ; 72
	tilecoll WALL, WALL, FLOOR, FLOOR ; 73
	tilecoll WALL, FLOOR, WALL, FLOOR ; 74
	tilecoll WALL, WALL, WALL, WALL ; 75
	tilecoll WALL, WALL, WALL, WALL ; 76
	tilecoll WALL, FLOOR, WALL, FLOOR ; 77
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 78
	tilecoll WALL, WALL, WALL, FLOOR ; 79
	tilecoll WALL, WALL, WALL, FLOOR ; 7a
	tilecoll WALL, WALL, WALL, WALL ; 7b
	tilecoll DOOR, WALL, FLOOR, FLOOR ; 7c
	tilecoll STAIRCASE, WALL, FLOOR, FLOOR ; 7d
	tilecoll WALL, FLOOR, WALL, COUNTER ; 7e
	tilecoll WALL, WALL, WALL, FLOOR ; 7f
; M6 9w: ROCKET HIDEOUT B2F/B3F spin maze -- each row is the
; block named after it with COLL_WALK_* painted into the
; quadrants Yellow's arrow runs pass through (same artwork).
	tilecoll WALK_CONTINUE, WALK_DOWN, WALK_UP, WALK_CONTINUE ; 80  from $02
	tilecoll WALK_CONTINUE, WALK_RIGHT, WALK_RIGHT, WALK_CONTINUE ; 81  from $03
	tilecoll FLOOR, WALK_RIGHT, WALK_RIGHT, WALK_CONTINUE ; 82  from $03
	tilecoll WALL, WALK_CONTINUE, FLOOR, WALK_CONTINUE ; 83  from $0a
	tilecoll WALL, FLOOR, WALK_CONTINUE, WALK_CONTINUE ; 84  from $0a
	tilecoll WALK_CONTINUE, WALK_CONTINUE, WALK_CONTINUE, WALK_CONTINUE ; 85  from $0e
	tilecoll FLOOR, WALK_CONTINUE, WALK_CONTINUE, WALK_CONTINUE ; 86  from $0e
	tilecoll FLOOR, FLOOR, WALK_CONTINUE, WALK_CONTINUE ; 87  from $0e
	tilecoll WALK_CONTINUE, WALK_LEFT, WALK_CONTINUE, WALK_LEFT ; 88  from $0f
	tilecoll WALK_CONTINUE, WALL, WALK_CONTINUE, FLOOR ; 89  from $11
	tilecoll FLOOR, WALL, WALK_CONTINUE, WALK_CONTINUE ; 8a  from $11
	tilecoll WALL, WALL, FLOOR, WALK_CONTINUE ; 8b  from $13
	tilecoll FLOOR, WALL, WALK_CONTINUE, WALL ; 8c  from $15
	tilecoll WALK_UP, WALL, FLOOR, WALL ; 8d  from $17
	tilecoll WALK_UP, WALL, WALK_CONTINUE, WALL ; 8e  from $17
	tilecoll WALL, WALL, WALK_CONTINUE, WALK_CONTINUE ; 8f  from $19
	tilecoll WALL, FLOOR, WALK_LEFT, FLOOR ; 90  from $1b
	tilecoll WALL, FLOOR, WALK_LEFT, WALK_CONTINUE ; 91  from $1b
	tilecoll WALK_CONTINUE, WALL, WALK_CONTINUE, WALL ; 92  from $20
	tilecoll FLOOR, WALL, WALK_RIGHT, WALK_CONTINUE ; 93  from $26
	tilecoll WALK_CONTINUE, WALK_RIGHT, WALK_UP, FLOOR ; 94  from $27
	tilecoll WALK_CONTINUE, FLOOR, WALL, WALL ; 95  from $29
