; TILESET_KANTO_BEACH_HOUSE -- generated by scripts/kanto_beach_house_blk.py
; from Yellow's beach_house blockset and its BeachHouse_Coll whitelist.  Do
; not hand-edit: `scripts/kanto_beach_house_blk.py --check` diffs it.  Warp
; overrides live in that script's WARPS.
	tilecoll WALL, WALL, WALL, WALL ; 00  ; unusable in GSC; SummerBeachHouse.blk does not use block $00
	tilecoll FLOOR, WALL, FLOOR, WALL ; 01
	tilecoll WALL, FLOOR, WALL, FLOOR ; 02
	tilecoll WALL, WALL, FLOOR, FLOOR ; 03
	tilecoll WALL, WALL, WALL, WALL ; 04
	tilecoll WALL, WALL, FLOOR, FLOOR ; 05
	tilecoll WALL, WALL, FLOOR, FLOOR ; 06
	tilecoll WALL, WALL, FLOOR, FLOOR ; 07
	tilecoll WALL, WALL, FLOOR, WALL ; 08
	tilecoll WALL, WALL, FLOOR, FLOOR ; 09
	tilecoll WALL, WALL, WALL, WALL ; 0a
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 0b  ; warp override: the south exit mat
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0f
	tilecoll WALL, WALL, FLOOR, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
