; TILESET_KANTO_GYM -- generated by scripts/kanto_gym_blk.py from
; Yellow's gym blockset and its Gym_Coll whitelist.  Do not hand-edit:
; `scripts/kanto_gym_blk.py --check` diffs it against the source.
	tilecoll WALL, WALL, WALL, WALL ; 00  ; unusable in GSC
	tilecoll WALL, WALL, FLOOR, FLOOR ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll WALL, WALL, WALL, WALL ; 03
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 04  ; warp override: the south exit mat
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 05
	tilecoll FLOOR, FLOOR, WALL, WALL ; 06
	tilecoll FLOOR, FLOOR, WALL, WALL ; 07
	tilecoll WALL, WALL, WALL, FLOOR ; 08
	tilecoll WALL, WALL, FLOOR, WALL ; 09
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0a
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0b
	tilecoll WALL, FLOOR, WALL, WALL ; 0c
	tilecoll FLOOR, WALL, WALL, WALL ; 0d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0f
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 10
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 11
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 12
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 13
	tilecoll WALL, WALL, FLOOR, FLOOR ; 14
	tilecoll FLOOR, WALL, FLOOR, WALL ; 15
	tilecoll WALL, FLOOR, WALL, FLOOR ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 18
	tilecoll WALL, FLOOR, WALL, FLOOR ; 19
	tilecoll WALL, WALL, WALL, WALL ; 1a
	tilecoll FLOOR, FLOOR, WALL, WALL ; 1b
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 1e
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 1f
	tilecoll WALL, WALL, WALL, WALL ; 20
	tilecoll WALL, WALL, WALL, WALL ; 21
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 22
	tilecoll WALL, WALL, FLOOR, FLOOR ; 23
	tilecoll WALL, WALL, FLOOR, FLOOR ; 24
	tilecoll WALL, WALL, FLOOR, FLOOR ; 25
	tilecoll WALL, WALL, WALL, WALL ; 26
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 27
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 28
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 29
	tilecoll WALL, WALL, WALL, WALL ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll WALL, WALL, WALL, WALL ; 2c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 2d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2e
	tilecoll WALL, FLOOR, WALL, FLOOR ; 2f
	tilecoll FLOOR, WALL, FLOOR, WALL ; 30
	tilecoll WALL, FLOOR, WALL, FLOOR ; 31
	tilecoll FLOOR, WALL, FLOOR, WALL ; 32
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 33
	tilecoll WALL, WALL, WALL, WALL ; 34
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 35
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 36
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 37
	tilecoll WALL, WALL, WALL, FLOOR ; 38
	tilecoll WALL, WALL, FLOOR, WALL ; 39
	tilecoll WALL, WALL, FLOOR, FLOOR ; 3a
	tilecoll WALL, FLOOR, WALL, WALL ; 3b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3c
	tilecoll FLOOR, WALL, FLOOR, WALL ; 3d
	tilecoll FLOOR, WALL, WALL, WALL ; 3e
	tilecoll FLOOR, FLOOR, WALL, WALL ; 3f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 40
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 41
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 42
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 43
	tilecoll WALL, WALL, WALL, WALL ; 44
	tilecoll WALL, WALL, WALL, WALL ; 45
	tilecoll FLOOR, FLOOR, WALL, WALL ; 46
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 47
	tilecoll WALL, WALL, FLOOR, FLOOR ; 48
	tilecoll WALL, WALL, WALL, FLOOR ; 49
	tilecoll WALL, WALL, FLOOR, WALL ; 4a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 4b
	tilecoll FLOOR, WALL, FLOOR, WALL ; 4c
	tilecoll WALL, WALL, FLOOR, WALL ; 4d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 4f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 50
	tilecoll FLOOR, WALL, FLOOR, WALL ; 51
	tilecoll WALL, FLOOR, WALL, WALL ; 52
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 53
	tilecoll WALL, FLOOR, FLOOR, WALL ; 54
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 55
	tilecoll FLOOR, FLOOR, WALL, WALL ; 56
	tilecoll FLOOR, FLOOR, WALL, WALL ; 57
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 58
	tilecoll FLOOR, FLOOR, WALL, WALL ; 59
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5a
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 5b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 5e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5f
	tilecoll FLOOR, WALL, FLOOR, WALL ; 60
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 61
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 62
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 63
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 64
	tilecoll WALL, WALL, WALL, WALL ; 65
	tilecoll WALL, WALL, WALL, WALL ; 66
	tilecoll WALL, WALL, FLOOR, FLOOR ; 67
	tilecoll WALL, WALL, WALL, WALL ; 68
	tilecoll FLOOR, FLOOR, WALL, WALL ; 69
	tilecoll FLOOR, FLOOR, WALL, WALL ; 6a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 6b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 6c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 6d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 6e
	tilecoll FLOOR, WALL, WALL, WALL ; 6f
	tilecoll FLOOR, WALL, FLOOR, WALL ; 70  ; TL is Yellow's warp tile $4a (E4 door): 13f+ decides
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 71
	tilecoll WALL, WALL, WALL, FLOOR ; 72
	tilecoll WALL, WALL, FLOOR, WALL ; 73
; D115 clones: Yellow's art, Viridian arrow-run collision
	tilecoll WALL, WALL, WALK_CONTINUE, WALK_CONTINUE ; 74 = $01, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALK_CONTINUE, WALK_CONTINUE, WALK_CONTINUE ; 75 = $05, VIRIDIAN GYM run
	tilecoll FLOOR, FLOOR, WALK_CONTINUE, WALK_CONTINUE ; 76 = $05, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, FLOOR, WALK_CONTINUE, FLOOR ; 77 = $40, VIRIDIAN GYM run
	tilecoll FLOOR, FLOOR, WALK_CONTINUE, WALK_CONTINUE ; 78 = $41, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALK_LEFT, WALK_CONTINUE, WALK_LEFT ; 79 = $42, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALK_CONTINUE, WALK_UP, WALK_UP ; 7a = $43, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALK_CONTINUE, WALL, WALL ; 7b = $46, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALK_CONTINUE, FLOOR, WALK_UP ; 7c = $47, VIRIDIAN GYM run
	tilecoll WALL, WALL, WALK_CONTINUE, WALK_CONTINUE ; 7d = $48, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALL, WALK_CONTINUE, WALL ; 7e = $4c, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALL, WALK_CONTINUE, FLOOR ; 7f = $55, VIRIDIAN GYM run
	tilecoll WALK_RIGHT, WALK_CONTINUE, WALL, WALL ; 80 = $57, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, WALL, FLOOR, WALK_RIGHT ; 81 = $58, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, FLOOR, WALL, WALL ; 82 = $59, VIRIDIAN GYM run
	tilecoll WALL, WALL, WALK_CONTINUE, FLOOR ; 83 = $5a, VIRIDIAN GYM run
	tilecoll WALK_DOWN, FLOOR, WALK_CONTINUE, WALK_CONTINUE ; 84 = $5c, VIRIDIAN GYM run
	tilecoll WALL, WALL, WALK_CONTINUE, WALK_LEFT ; 85 = $5d, VIRIDIAN GYM run
	tilecoll WALK_CONTINUE, FLOOR, WALL, WALL ; 86 = $5e, VIRIDIAN GYM run
	tilecoll WALK_DOWN, WALL, WALK_CONTINUE, WALL ; 87 = $60, VIRIDIAN GYM run
	tilecoll FLOOR, WALK_RIGHT, FLOOR, WALL ; 88 = $63, VIRIDIAN GYM run
; M10 13j: E4 exit twins (scripts/kanto_gym_blk.py E4_CLONES)
	tilecoll WARP_CARPET_UP, WARP_CARPET_UP, FLOOR, FLOOR ; 89 = $05, LORELEI/BRUNO exit, open (callback)
	tilecoll WALL, WARP_CARPET_UP, WALL, FLOOR ; 8a = $31, LANCE exit (5,0)
	tilecoll WARP_CARPET_UP, WALL, FLOOR, WALL ; 8b = $32, LANCE exit (6,0)
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 8c = $05, LORELEI/BRUNO entrance once the League is open (post-E4)
	tilecoll WARP_PANEL, WALL, FLOOR, WALL ; 8d = $70, LANCE entrance (24,16) once the League is open
	tilecoll WALL, FLOOR, WALL, WARP_CARPET_DOWN ; 8e = $31, CHAMPION entrance (3,7)
	tilecoll FLOOR, WALL, WARP_CARPET_DOWN, WALL ; 8f = $32, CHAMPION entrance (4,7)
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 90 = $6c, HALL OF FAME entrance (4,7)/(5,7)
