/* Kanto First - save editor for the browser player.
 *
 * Same origin, same IndexedDB, same battery record as app.js: this page reads
 * `battery:<titleKey>`, lets you change the parts of the save a player might
 * reasonably want to change, writes BOTH save copies back with fresh
 * checksums, deletes the `resume:` snapshot (otherwise the emulator would
 * restore the pre-edit machine state and your edit would vanish) and sends you
 * back to the player, which then power-ons from the edited cartridge RAM.
 *
 * Nothing about the save format is hardcoded here.  web/tables.json is
 * generated by web/gen_tables.py from pokecrystal.sym + constants/*.asm at
 * build time (`make crystal`), and carries the SRAM offsets, the party struct
 * layout, the name tables, the base-stat/growth-rate table addresses and the
 * sha256 of the ROM it was generated from.  If the loaded ROM's sha does not
 * match that stamp the editor refuses to write anything: the offsets would be
 * for a different build.
 *
 * The one thing that is NOT derived is arithmetic: the stat and experience
 * formulas below are a transcription of CalcMonStatC and CalcExpAtLevel
 * (engine/pokemon/move_mon.asm, engine/pokemon/experience.asm).  They read
 * their inputs out of the ROM image this page already fetched.
 */
(function () {
  'use strict';

  var DEFAULT_ROM = './kanto-first.gbc';
  var TABLES_URL = './tables.json';
  var PRESET_DIR = './presets/';
  var SAV_NAME = 'kanto-first.sav';

  var DB_NAME = 'kanto-first-web';
  var DB_VERSION = 1;
  var STORE = 'kv';

  var T = null;               // tables.json
  var rom = null;
  var romSha = null;
  var titleKey = null;
  var sav = null;             // the working 32 KiB image (edited in place)
  var original = null;        // the battery bytes exactly as loaded
  var haveSave = false;
  var canWrite = false;
  var party = [];             // 6 slots: null, or {mon, nick, ot}
  var bag = {};               // pocket id -> [{id, qty}] (tm pocket: qty array)
  var dirty = false;

  function $(sel) { return document.querySelector(sel); }
  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) { n.className = cls; }
    if (text !== undefined) { n.textContent = text; }
    return n;
  }

  var statusEl = null;
  function say(msg, bad) {
    statusEl.textContent = msg;
    statusEl.className = bad ? 'err' : '';
  }

  // --------------------------------------------------------------- sha256 ---
  /* crypto.subtle only exists in a secure context and the operator may well
     host this over plain http on a LAN, so keep the same pure-JS fallback
     app.js uses. */
  var KK = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2];

  function sha256Sync(bytes) {
    var h = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
    var len = bytes.length, withPad = ((len + 9 + 63) >> 6) << 6;
    var m = new Uint8Array(withPad);
    m.set(bytes);
    m[len] = 0x80;
    var bits = len * 8, i;
    m[withPad - 1] = bits & 0xff;
    m[withPad - 2] = (bits / 0x100) & 0xff;
    m[withPad - 3] = (bits / 0x10000) & 0xff;
    m[withPad - 4] = (bits / 0x1000000) & 0xff;
    m[withPad - 5] = (bits / 0x100000000) & 0xff;
    m[withPad - 6] = (bits / 0x10000000000) & 0xff;
    var w = new Int32Array(64);
    for (var off = 0; off < withPad; off += 64) {
      for (i = 0; i < 16; i++) {
        w[i] = (m[off + i * 4] << 24) | (m[off + i * 4 + 1] << 16) | (m[off + i * 4 + 2] << 8) | m[off + i * 4 + 3];
      }
      for (i = 16; i < 64; i++) {
        var g0 = w[i - 15], g1 = w[i - 2];
        var s0 = ((g0 >>> 7) | (g0 << 25)) ^ ((g0 >>> 18) | (g0 << 14)) ^ (g0 >>> 3);
        var s1 = ((g1 >>> 17) | (g1 << 15)) ^ ((g1 >>> 19) | (g1 << 13)) ^ (g1 >>> 10);
        w[i] = (w[i - 16] + s0 + w[i - 7] + s1) | 0;
      }
      var a = h[0], b = h[1], c = h[2], d = h[3], e = h[4], f = h[5], gg = h[6], hh = h[7];
      for (i = 0; i < 64; i++) {
        var S1 = ((e >>> 6) | (e << 26)) ^ ((e >>> 11) | (e << 21)) ^ ((e >>> 25) | (e << 7));
        var ch = (e & f) ^ (~e & gg);
        var t1 = (hh + S1 + ch + KK[i] + w[i]) | 0;
        var S0 = ((a >>> 2) | (a << 30)) ^ ((a >>> 13) | (a << 19)) ^ ((a >>> 22) | (a << 10));
        var maj = (a & b) ^ (a & c) ^ (b & c);
        var t2 = (S0 + maj) | 0;
        hh = gg; gg = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0;
      }
      h[0] = (h[0] + a) | 0; h[1] = (h[1] + b) | 0; h[2] = (h[2] + c) | 0; h[3] = (h[3] + d) | 0;
      h[4] = (h[4] + e) | 0; h[5] = (h[5] + f) | 0; h[6] = (h[6] + gg) | 0; h[7] = (h[7] + hh) | 0;
    }
    var out = '';
    for (i = 0; i < 8; i++) { out += ('00000000' + (h[i] >>> 0).toString(16)).slice(-8); }
    return out;
  }

  function sha256(bytes) {
    if (window.crypto && window.crypto.subtle && window.crypto.subtle.digest) {
      var copy = bytes.slice(0);
      return window.crypto.subtle.digest('SHA-256', copy.buffer).then(function (buf) {
        var v = new Uint8Array(buf), s = '', i;
        for (i = 0; i < v.length; i++) { s += (v[i] < 16 ? '0' : '') + v[i].toString(16); }
        return s;
      }).catch(function () { return sha256Sync(bytes); });
    }
    return Promise.resolve(sha256Sync(bytes));
  }

  // ------------------------------------------------------------ IndexedDB ---

  var dbPromise = null;
  function db() {
    if (!dbPromise) {
      dbPromise = new Promise(function (resolve, reject) {
        var req = indexedDB.open(DB_NAME, DB_VERSION);
        req.onupgradeneeded = function () {
          if (!req.result.objectStoreNames.contains(STORE)) { req.result.createObjectStore(STORE); }
        };
        req.onsuccess = function () { resolve(req.result); };
        req.onerror = function () { reject(req.error); };
        req.onblocked = function () { reject(new Error('IndexedDB blocked')); };
      });
    }
    return dbPromise;
  }
  function tx(mode, fn) {
    return db().then(function (d) {
      return new Promise(function (resolve, reject) {
        var t = d.transaction(STORE, mode);
        var req = fn(t.objectStore(STORE));
        t.oncomplete = function () { resolve(req ? req.result : undefined); };
        t.onerror = function () { reject(t.error); };
        t.onabort = function () { reject(t.error); };
      });
    });
  }
  function kvGet(k) { return tx('readonly', function (s) { return s.get(k); }); }
  function kvPut(k, v) { return tx('readwrite', function (s) { return s.put(v, k); }); }
  function kvDel(k) { return tx('readwrite', function (s) { return s.delete(k); }); }

  function batteryKey() { return 'battery:' + titleKey; }
  function backupKey() { return 'battery-backup:' + titleKey; }
  function resumeKey() { return 'resume:' + titleKey; }

  /* Same save-region signature app.js stores in every battery/resume record:
     FNV-1a over cartridge RAM from $600 on (past sScratch, the decompression
     scratch area).  Keep in step with sig()/saveSig() in app.js. */
  function saveSig(ram) {
    var bytes = ram.subarray(Math.min(0x600, ram.length));
    var h = 0x811c9dc5;
    for (var i = 0; i < bytes.length; i++) {
      h ^= bytes[i];
      h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
    }
    return h + ':' + bytes.length;
  }

  // ------------------------------------------------------------- ROM load ---

  function titleKeyOf(r) {
    var t = '';
    for (var i = 0x134; i < 0x144; i++) {
      var c = r[i];
      if (c >= 0x20 && c <= 0x7e) { t += String.fromCharCode(c); }
    }
    return (t.replace(/[^A-Za-z0-9_.-]/g, '') || 'UNKNOWN') + '-' + r[0x147].toString(16);
  }

  function fetchBytes(url) {
    return fetch(url, { cache: 'no-store' }).then(function (r) {
      if (!r.ok) { throw new Error(url + ' -> HTTP ' + r.status); }
      return r.arrayBuffer();
    }).then(function (buf) { return new Uint8Array(buf); });
  }

  function loadRom() {
    var params = new URLSearchParams(window.location.search);
    var override = params.get('rom');
    if (override) { return fetchBytes(override); }
    return fetchBytes(DEFAULT_ROM).catch(function (e) {
      return kvGet('rom:last').then(function (stash) {
        if (stash && stash.rom && stash.rom.length) { return new Uint8Array(stash.rom); }
        throw e;
      });
    });
  }

  function readFile(file) {
    return new Promise(function (resolve, reject) {
      var fr = new FileReader();
      fr.onload = function () { resolve(new Uint8Array(fr.result)); };
      fr.onerror = function () { reject(fr.error); };
      fr.readAsArrayBuffer(file);
    });
  }

  function download(name, bytes) {
    var url = URL.createObjectURL(new Blob([bytes], { type: 'application/octet-stream' }));
    var a = document.createElement('a');
    a.href = url;
    a.download = name;
    a.rel = 'noopener';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(function () { URL.revokeObjectURL(url); }, 4000);
  }

  // ------------------------------------------------------- SRAM primitives ---

  function normalizeSram(bytes) {
    var size = T.sav.size;
    if (bytes.length === size) { return bytes.slice(0); }
    var out = new Uint8Array(size);
    out.set(bytes.subarray(0, Math.min(bytes.length, size)));
    return out;
  }

  function off(name) {
    var f = T.fields[name];
    if (!f) { throw new Error('tables.json has no field ' + name); }
    return f[0];
  }
  function len(name) { return T.fields[name][1]; }
  function rd8(name) { return sav[off(name)]; }
  function wr8(name, v) { sav[off(name)] = v & 0xff; }
  function rdBE(name, n) {
    var o = off(name), v = 0;
    for (var i = 0; i < n; i++) { v = v * 256 + sav[o + i]; }
    return v;
  }
  function wrBE(name, n, v) {
    var o = off(name);
    for (var i = n - 1; i >= 0; i--) { sav[o + i] = v & 0xff; v = Math.floor(v / 256); }
  }

  function checksumOf(c) {
    var s = 0;
    for (var i = c.gameData; i < c.gameDataEnd; i++) { s = (s + sav[i]) & 0xffff; }
    return s;
  }
  function copyOk(c) {
    var stored = sav[c.checksum] | (sav[c.checksum + 1] << 8);
    return stored === checksumOf(c) &&
      sav[c.checkValue1] === T.sav.checkValue1 &&
      sav[c.checkValue2] === T.sav.checkValue2;
  }

  /* Write the save the way _SaveGameData does: the backup copy is a verbatim
     duplicate of the primary (the whole span is a uniform -0x0E00 shift, and
     gen_tables.py asserts that at build time), both magic bytes set, both
     checksums recomputed.  Editing only one copy is the classic way to lose an
     edit: the loader falls back to the other copy and silently reverts you. */
  function finalize() {
    var P = T.sav.copies[0], B = T.sav.copies[1];
    var from = P.options, to = P.checkValue2 + 1;
    sav.set(sav.subarray(from, to), from + T.sav.backupDelta);
    [P, B].forEach(function (c) {
      sav[c.checkValue1] = T.sav.checkValue1;
      sav[c.checkValue2] = T.sav.checkValue2;
      var s = checksumOf(c);
      sav[c.checksum] = s & 0xff;
      sav[c.checksum + 1] = (s >> 8) & 0xff;
    });
  }

  // ------------------------------------------------------------- charmap ----

  var decMap = null;
  function decodeTable() {
    if (decMap) { return decMap; }
    decMap = {};
    Object.keys(T.charmap).forEach(function (ch) {
      var b = T.charmap[ch];
      var cur = decMap[b];
      // prefer a plain ASCII spelling when several characters share a byte
      if (cur === undefined || (ch.charCodeAt(0) < 128 && cur.charCodeAt(0) >= 128)) { decMap[b] = ch; }
    });
    return decMap;
  }
  var TERM = 0x50;   // "@"
  function decodeName(o, n) {
    var m = decodeTable(), out = '';
    for (var i = 0; i < n; i++) {
      var b = sav[o + i];
      if (b === TERM || b === 0) { break; }
      out += m[b] !== undefined ? m[b] : '?';
    }
    return out;
  }
  function encodeName(str, o, n) {
    var i = 0, j = 0;
    for (; i < str.length && j < n - 1; i++) {
      var ch = str[i];
      var b = T.charmap[ch];
      if (b === undefined) { b = T.charmap[ch.toUpperCase()]; }
      if (b === undefined) { continue; }
      sav[o + j] = b;
      j++;
    }
    for (; j < n; j++) { sav[o + j] = TERM; }
  }
  function nameIsEncodable(str) {
    for (var i = 0; i < str.length; i++) {
      if (T.charmap[str[i]] === undefined && T.charmap[str[i].toUpperCase()] === undefined) { return false; }
    }
    return true;
  }

  // ------------------------------------------------------ stats / exp -------
  /* CalcMonStatC (engine/pokemon/move_mon.asm) and CalcExpAtLevel
     (engine/pokemon/experience.asm), transcribed.  Inputs come out of the ROM
     image, so these stay correct across rebalances of the base-stat table. */

  function baseStat(species, key) {
    var bs = T.baseStats;
    return rom[bs.rom + (species - 1) * bs.stride + bs.fields[key]];
  }

  function sqrtIndex(v) {
    // GetSquareRoot: the index of the first square that is not lower than v.
    var n = T.limits.numSquareRoots;
    for (var b = 1; b < n; b++) { if (b * b >= v) { return b; } }
    return n;
  }

  var STAT_KEYS = ['hp', 'atk', 'def', 'spd', 'sat', 'sdf'];

  function dvFor(dvs, idx) {
    var atk = (dvs[0] >> 4) & 0xf, def = dvs[0] & 0xf;
    var spd = (dvs[1] >> 4) & 0xf, spc = dvs[1] & 0xf;
    if (idx === 1) { return atk; }
    if (idx === 2) { return def; }
    if (idx === 3) { return spd; }
    if (idx === 4 || idx === 5) { return spc; }
    return ((atk & 1) << 3) | ((def & 1) << 2) | ((spd & 1) << 1) | (spc & 1);
  }

  function calcStat(species, idx, dvs, statExpWords, level) {
    var base = baseStat(species, STAT_KEYS[idx]);
    var dv = dvFor(dvs, idx);
    // STAT_SDEF shares STAT_SATK's stat experience word
    var se = statExpWords[idx === 5 ? 4 : (idx === 0 ? 0 : idx)] || 0;
    var x = (base + dv) * 2 + (sqrtIndex(se) >> 2);
    var v = Math.floor(x * level / 100);
    v += idx === 0 ? (level + T.limits.statMinHP) : T.limits.statMinNormal;
    return Math.min(v, T.limits.maxStatValue);
  }

  function expAtLevel(species, level) {
    var g = rom[T.baseStats.rom + (species - 1) * T.baseStats.stride + T.baseStats.fields.growthRate];
    var r = T.growthRates[g];
    if (!r) { return 0; }
    var n = level;
    // (a/b)*n^3 + c*n^2 + d*n - e, the cubic term truncated like the game's divide
    var v = Math.floor(r[0] * n * n * n / r[1]) + r[2] * n * n + r[3] * n - r[4];
    // The game underflows here for a level-1 Medium Slow mon (a documented
    // bug); clamping is the sane thing for an editor to do instead.
    if (v < 0) { v = 0; }
    return Math.min(v, 0xffffff);
  }

  function movePP(move) {
    if (!move) { return 0; }
    var ms = T.moveStats;
    return rom[ms.rom + (move - 1) * ms.stride + ms.fields.pp];
  }

  // -------------------------------------------------------- the party ------

  var P = null;   // T.party shorthand

  function monField(mon, key) { return mon[P.mon[key]]; }
  function monWord(mon, key) { return (mon[P.mon[key]] << 8) | mon[P.mon[key] + 1]; }
  function setMonWord(mon, key, v) {
    mon[P.mon[key]] = (v >> 8) & 0xff;
    mon[P.mon[key] + 1] = v & 0xff;
  }

  function statExpWords(mon) {
    var o = P.mon.statExp, out = [];
    for (var i = 0; i < 5; i++) { out.push((mon[o + i * 2] << 8) | mon[o + i * 2 + 1]); }
    return out;
  }

  /* Recompute max HP and the five stats, set EXP to the minimum for the
     mon's level, refill PP, and (heal) put current HP at max. */
  function recalcMon(slot, heal) {
    var mon = slot.mon;
    var species = mon[P.mon.species];
    var level = mon[P.mon.level];
    var dvs = [mon[P.mon.dvs], mon[P.mon.dvs + 1]];
    var se = statExpWords(mon);
    var maxHp = calcStat(species, 0, dvs, se, level);
    setMonWord(mon, 'maxHp', maxHp);
    for (var i = 1; i < 6; i++) {
      var v = calcStat(species, i, dvs, se, level);
      mon[P.mon.stats + (i - 1) * 2] = (v >> 8) & 0xff;
      mon[P.mon.stats + (i - 1) * 2 + 1] = v & 0xff;
    }
    var xp = expAtLevel(species, level);   // exp is a 3-byte big-endian field
    mon[P.mon.exp] = (xp >> 16) & 0xff;
    mon[P.mon.exp + 1] = (xp >> 8) & 0xff;
    mon[P.mon.exp + 2] = xp & 0xff;
    for (var m = 0; m < P.numMoves; m++) { mon[P.mon.pp + m] = movePP(mon[P.mon.moves + m]); }
    if (heal) {
      setMonWord(mon, 'hp', maxHp);
      mon[P.mon.status] = 0;
    } else if (monWord(mon, 'hp') > maxHp) {
      setMonWord(mon, 'hp', maxHp);
    }
  }

  function newMon(species, level) {
    var mon = new Uint8Array(P.stride);
    mon[P.mon.species] = species;
    mon[P.mon.level] = level;
    mon[P.mon.dvs] = 0xff;             // 15 in every DV: predictable, and good
    mon[P.mon.dvs + 1] = 0xff;
    mon[P.mon.happiness] = T.limits.baseHappiness;
    mon[P.mon.id] = sav[off('wPlayerID')];
    mon[P.mon.id + 1] = sav[off('wPlayerID') + 1];
    return mon;
  }

  function readParty() {
    party = [];
    var count = rd8('wPartyCount');
    var mons = off('wPartyMons'), ots = off('wPartyMonOTs'), nicks = off('wPartyMonNicknames');
    for (var i = 0; i < P.length; i++) {
      if (i >= count) { party.push(null); continue; }
      party.push({
        mon: sav.slice(mons + i * P.stride, mons + (i + 1) * P.stride),
        ot: sav.slice(ots + i * P.otLength, ots + (i + 1) * P.otLength),
        nick: sav.slice(nicks + i * P.nickLength, nicks + (i + 1) * P.nickLength)
      });
    }
  }

  function writeParty() {
    var filled = party.filter(function (s) { return s; });
    var mons = off('wPartyMons'), ots = off('wPartyMonOTs'), nicks = off('wPartyMonNicknames');
    var spec = off('wPartySpecies');
    sav[off('wPartyCount')] = filled.length;
    for (var i = 0; i < P.length; i++) {
      var s = filled[i];
      sav[spec + i] = s ? s.mon[P.mon.species] : 0;
      if (s) {
        sav.set(s.mon, mons + i * P.stride);
        sav.set(s.ot, ots + i * P.otLength);
        sav.set(s.nick, nicks + i * P.nickLength);
      } else {
        sav.fill(0, mons + i * P.stride, mons + (i + 1) * P.stride);
        sav.fill(TERM, ots + i * P.otLength, ots + (i + 1) * P.otLength);
        sav.fill(TERM, nicks + i * P.nickLength, nicks + (i + 1) * P.nickLength);
      }
    }
    sav[spec + filled.length] = 0xff;   // the party list's terminator
    // keep the UI's model in the compacted order the cartridge uses
    party = filled.concat(new Array(P.length - filled.length).fill(null));
  }

  // ---------------------------------------------------------------- bag -----

  /* Pocket layout (engine/items/pack.asm + the wNum*/ /* fields):
     a count byte, then `entry` bytes per slot, then a $ff terminator.  The
     TM/HM pocket is different: wTMsHMs is a flat quantity-per-TM array. */
  var POCKETS = [
    { id: 'item', label: 'Items', count: 'wNumItems', list: 'wItems', entry: 2, cap: 'maxItems' },
    { id: 'ball', label: 'Balls', count: 'wNumBalls', list: 'wBalls', entry: 2, cap: 'maxBalls' },
    { id: 'key', label: 'Key items', count: 'wNumKeyItems', list: 'wKeyItems', entry: 1, cap: 'maxKeyItems' }
  ];

  function readBag() {
    bag = {};
    POCKETS.forEach(function (p) {
      var n = Math.min(sav[off(p.count)], T.limits[p.cap]);
      var o = off(p.list), out = [];
      for (var i = 0; i < n; i++) {
        var id = sav[o + i * p.entry];
        if (!id || id === 0xff) { break; }
        out.push({ id: id, qty: p.entry === 2 ? sav[o + i * p.entry + 1] : 1 });
      }
      bag[p.id] = out;
    });
    bag.tm = Array.prototype.slice.call(sav.subarray(off('wTMsHMs'), off('wTMsHMs') + len('wTMsHMs')));
  }

  function writeBag() {
    POCKETS.forEach(function (p) {
      var o = off(p.list), cap = T.limits[p.cap], list = bag[p.id].slice(0, cap);
      sav[off(p.count)] = list.length;
      for (var i = 0; i < cap; i++) {
        if (i < list.length) {
          sav[o + i * p.entry] = list[i].id;
          if (p.entry === 2) { sav[o + i * p.entry + 1] = list[i].qty; }
        } else {
          sav[o + i * p.entry] = 0;
          if (p.entry === 2) { sav[o + i * p.entry + 1] = 0; }
        }
      }
      sav[o + list.length * p.entry] = 0xff;
    });
    sav.set(bag.tm, off('wTMsHMs'));
  }

  // ------------------------------------------------------------- events -----

  function eventGet(id) { return (sav[off('wEventFlags') + (id >> 3)] >> (id & 7)) & 1; }
  function eventSet(id, on) {
    var o = off('wEventFlags') + (id >> 3), m = 1 << (id & 7);
    if (on) { sav[o] |= m; } else { sav[o] &= ~m & 0xff; }
  }

  // ============================================================== the UI ====

  function markDirty() {
    dirty = true;
    $('#btn-apply').disabled = !canWrite;
  }

  function optionsHtml(list, blank) {
    var html = blank ? '<option value="0">' + blank + '</option>' : '';
    var glitch = false;
    for (var i = 0; i < list.length; i++) {
      // WEB6: glitch species (252 MISSINGNO.) sit last, in their own group
      if (list[i].glitch && !glitch) { html += '<optgroup label="Glitch">'; glitch = true; }
      html += '<option value="' + list[i].id + '">' + esc(list[i].name) + '</option>';
    }
    if (glitch) { html += '</optgroup>'; }
    return html;
  }
  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  // ---- location
  function buildSpawns() {
    var sel = $('#f-spawn');
    var groups = { kanto: el('optgroup'), johto: el('optgroup') };
    groups.kanto.label = 'Kanto';
    groups.johto.label = 'Johto';
    var keep = el('option', null, '— leave me where I am —');
    keep.value = '';
    sel.appendChild(keep);
    T.spawns.forEach(function (s, i) {
      var o = el('option', null, s.label);
      o.value = String(i);
      (groups[s.region] || groups.kanto).appendChild(o);
    });
    ['kanto', 'johto'].forEach(function (k) {
      if (groups[k].children.length) { sel.appendChild(groups[k]); }
    });
    sel.value = '';
    sel.addEventListener('change', function () {
      if (sel.value === '') { return; }
      putMeIn(T.spawns[+sel.value]);
      showWhere();
      markDirty();
    });
    showWhere();
  }

  // "Put me in X" is more than wMapGroup/wMapNumber/wXCoord/wYCoord.  The
  // continue path (MapSetupScript_Continue, data/maps/setup_scripts.asm) calls
  // LoadMapAttributes_SkipObjects -- it never runs SpawnPlayer and never loads
  // the new map's object events -- and then LoadConnectionBlockData copies the
  // saved 6x5 metatile window (wScreenSave) straight back over the blocks
  // around the player.  Everything below is therefore state the game would
  // normally have built while walking, and that we have to build ourselves:
  //   * the player's (and the follower's) object struct + map object, which
  //     otherwise still hold the OLD map's coordinates -- the player ends up
  //     off-map and cannot take a single step;
  //   * wScreenSave, which otherwise paints a 6x5 patch of the old map over
  //     the new one (gen_tables.py precomputes the right window from the ROM);
  //   * the old map's NPCs, which would otherwise linger in wMapObjects /
  //     wObjectStructs.  We evict them; the real ones appear as soon as the
  //     player leaves the map and comes back.
  function putMeIn(s) {
    wr8('wMapGroup', s.group);
    wr8('wMapNumber', s.number);
    wr8('wXCoord', s.x);
    wr8('wYCoord', s.y);
    wr8('wWarpNumber', 0);        // not mid-warp: the continue path uses coords
    // PlayerSpawn_ConvertCoords (engine/overworld/player_object.asm): map
    // object coords are tile coords + 4.
    var mx = (s.x + 4) & 0xff, my = (s.y + 4) & 0xff;
    var st = T.objects.standing;   // STANDING, constants/ram_constants.asm
    wr8('wPlayerObjectXCoord', mx);
    wr8('wPlayerObjectYCoord', my);
    // CopyTempObjectToObjectStruct: INIT/MAP coords, SPRITE_X/Y centred,
    // STEP_TYPE_RESET, FACING = STANDING.  The motion members matter as much
    // as the coordinates: a save captured mid-step resumes that step on the
    // new map, which on an open tile walks the player off it.
    ['wPlayer', 'wFollower'].forEach(function (pfx) {
      var geom = {
        MapX: mx, MapY: my, LastMapX: mx, LastMapY: my, InitX: mx, InitY: my,
        SpriteX: 0x40, SpriteY: 0x40, SpriteXOffset: 0, SpriteYOffset: 0,
        Walking: st, Facing: st, Direction: 0, StepType: 0, StepDuration: 0,
        StepFrame: 0, TileCollision: 0, LastTile: 0, MovementIndex: 0,
        StepIndex: 0, Field1d: 0, Field1e: 0, JumpHeight: 0
      };
      Object.keys(geom).forEach(function (k) {
        if (T.fields[pfx + k]) { wr8(pfx + k, geom[k]); }
      });
    });

    // the saved scene pointer still aims at the OLD map's scene id; point it
    // at the new map's scene variable (0 = this map has no scene scripts)
    var sp = off('wCurMapSceneScriptPointer');
    sav[sp] = s.scene & 0xff;
    sav[sp + 1] = (s.scene >> 8) & 0xff;

    // the metatile window the game would have buffered standing on that tile
    var o = off('wScreenSave'), n = Math.min(s.screen.length, len('wScreenSave'));
    for (var i = 0; i < n; i++) { sav[o + i] = s.screen[i] & 0xff; }

    // evict the old map's NPCs (object 0 is the player, struct 13 the follower)
    var ob = T.objects;
    for (i = 1; i < ob.numObjects; i++) {
      sav.fill(0, off('wMapObjects') + i * ob.mapObjectLength,
               off('wMapObjects') + (i + 1) * ob.mapObjectLength);
    }
    for (i = 1; i < ob.followerIndex; i++) {
      sav.fill(0, off('wObjectStructs') + i * ob.structLength,
               off('wObjectStructs') + (i + 1) * ob.structLength);
    }
    // arriving somewhere is what the game records for fly / blackout
    wr8('wLastSpawnMapGroup', s.group);
    wr8('wLastSpawnMapNumber', s.number);
    var vb = off('wVisitedSpawns') + (s.index >> 3);
    if (s.index >> 3 < len('wVisitedSpawns')) { sav[vb] |= 1 << (s.index & 7); }
  }

  function showWhere() {
    var g = rd8('wMapGroup'), n = rd8('wMapNumber');
    var hit = null;
    T.spawns.forEach(function (s) { if (s.group === g && s.number === n) { hit = s; } });
    $('#spawn-now').textContent = 'Currently: ' + (hit ? hit.label : 'map ' + g + '.' + n) +
      ' at (' + rd8('wXCoord') + ',' + rd8('wYCoord') + ')';
  }

  // ---- party
  var speciesOpts = null, moveOpts = null;

  function buildParty() {
    speciesOpts = optionsHtml(T.species, '— empty slot —');
    moveOpts = optionsHtml(T.moves, '— none —');
    renderParty();
    $('#btn-heal').addEventListener('click', function () {
      party.forEach(function (s) { if (s) { recalcMon(s, true); } });
      writeParty();
      renderParty();
      markDirty();
      say('Party healed and stats recalculated from the ROM.');
    });
  }

  function renderParty() {
    var host = $('#party');
    host.textContent = '';
    var n = party.filter(function (s) { return s; }).length;
    $('#party-count').textContent = n + '/' + P.length;
    for (var i = 0; i < P.length; i++) { host.appendChild(monCard(i)); }
  }

  function monCard(i) {
    var slot = party[i];
    var card = el('div', 'mon');
    card.appendChild(el('h3', null, 'Slot ' + (i + 1)));

    var spec = el('select');
    spec.innerHTML = speciesOpts;
    spec.value = slot ? String(slot.mon[P.mon.species]) : '0';
    card.appendChild(field('Species', spec));

    if (!slot) {
      spec.addEventListener('change', function () {
        var id = +spec.value;
        if (!id) { return; }
        var s = { mon: newMon(id, 5), ot: new Uint8Array(P.otLength), nick: new Uint8Array(P.nickLength) };
        s.ot.fill(TERM);
        s.nick.fill(TERM);
        var name = nameOf(T.species, id);
        savWriteInto(s.ot, decodeName(off('wPlayerName'), len('wPlayerName')));
        savWriteInto(s.nick, name);
        recalcMon(s, true);
        party[i] = s;
        writeParty();
        renderParty();
        markDirty();
      });
      return card;
    }

    spec.addEventListener('change', function () {
      var id = +spec.value;
      if (!id) {
        party[i] = null;
      } else {
        slot.mon[P.mon.species] = id;
        recalcMon(slot, true);
      }
      writeParty();
      renderParty();
      markDirty();
    });

    var lvl = numInput(slot.mon[P.mon.level], 1, T.limits.maxLevel);
    lvl.addEventListener('change', function () {
      slot.mon[P.mon.level] = clamp(+lvl.value, 1, T.limits.maxLevel);
      recalcMon(slot, true);
      writeParty();
      renderParty();
      markDirty();
    });
    card.appendChild(field('Level', lvl));

    var nick = el('input');
    nick.type = 'text';
    nick.maxLength = P.nickLength - 1;
    nick.value = decodeBytes(slot.nick);
    nick.addEventListener('change', function () {
      savWriteInto(slot.nick, nick.value);
      nick.value = decodeBytes(slot.nick);
      writeParty();
      markDirty();
    });
    card.appendChild(field('Nickname', nick));

    var moves = el('div', 'moves');
    for (var m = 0; m < P.numMoves; m++) {
      (function (m) {
        var mv = el('select');
        mv.innerHTML = moveOpts;
        mv.value = String(slot.mon[P.mon.moves + m]);
        mv.addEventListener('change', function () {
          slot.mon[P.mon.moves + m] = +mv.value;
          slot.mon[P.mon.pp + m] = movePP(+mv.value);
          compactMoves(slot);
          writeParty();
          renderParty();
          markDirty();
        });
        moves.appendChild(mv);
      }(m));
    }
    card.appendChild(moves);

    var maxHp = monWord(slot.mon, 'maxHp');
    var hp = numInput(monWord(slot.mon, 'hp'), 0, maxHp);
    hp.addEventListener('change', function () {
      setMonWord(slot.mon, 'hp', clamp(+hp.value, 0, monWord(slot.mon, 'maxHp')));
      hp.value = monWord(slot.mon, 'hp');
      writeParty();
      markDirty();
    });
    card.appendChild(field('HP (max ' + maxHp + ')', hp));

    var stats = [];
    for (var s2 = 0; s2 < 5; s2++) {
      stats.push((slot.mon[P.mon.stats + s2 * 2] << 8) | slot.mon[P.mon.stats + s2 * 2 + 1]);
    }
    var note = el('p', 'note', 'ATK ' + stats[0] + '  DEF ' + stats[1] + '  SPD ' + stats[2] +
      '  SPA ' + stats[3] + '  SPD(f) ' + stats[4] +
      '  · EXP ' + ((slot.mon[P.mon.exp] << 16) | (slot.mon[P.mon.exp + 1] << 8) | slot.mon[P.mon.exp + 2]));
    card.appendChild(note);

    var btn = el('button', null, 'Heal & recalculate');
    btn.type = 'button';
    btn.addEventListener('click', function () {
      recalcMon(slot, true);
      writeParty();
      renderParty();
      markDirty();
    });
    card.appendChild(btn);
    return card;
  }

  function compactMoves(slot) {
    // the game never leaves a gap in the move list
    var mv = [], pp = [], i;
    for (i = 0; i < P.numMoves; i++) {
      if (slot.mon[P.mon.moves + i]) {
        mv.push(slot.mon[P.mon.moves + i]);
        pp.push(slot.mon[P.mon.pp + i]);
      }
    }
    for (i = 0; i < P.numMoves; i++) {
      slot.mon[P.mon.moves + i] = mv[i] || 0;
      slot.mon[P.mon.pp + i] = pp[i] || 0;
    }
  }

  function nameOf(list, id) {
    for (var i = 0; i < list.length; i++) { if (list[i].id === id) { return list[i].name; } }
    return '?';
  }

  function decodeBytes(arr) {
    var m = decodeTable(), out = '';
    for (var i = 0; i < arr.length; i++) {
      if (arr[i] === TERM || arr[i] === 0) { break; }
      out += m[arr[i]] !== undefined ? m[arr[i]] : '?';
    }
    return out;
  }
  function savWriteInto(arr, str) {
    var j = 0;
    for (var i = 0; i < str.length && j < arr.length - 1; i++) {
      var b = T.charmap[str[i]];
      if (b === undefined) { b = T.charmap[str[i].toUpperCase()]; }
      if (b === undefined) { continue; }
      arr[j] = b;
      j++;
    }
    for (; j < arr.length; j++) { arr[j] = TERM; }
  }

  function field(label, node) {
    var l = el('label', 'field');
    l.appendChild(el('span', null, label));
    l.appendChild(node);
    return l;
  }
  function numInput(value, min, max) {
    var n = el('input');
    n.type = 'number';
    n.inputMode = 'numeric';
    n.min = String(min);
    n.max = String(max);
    n.value = String(value);
    return n;
  }
  function clamp(v, lo, hi) {
    if (isNaN(v)) { return lo; }
    return Math.max(lo, Math.min(hi, Math.round(v)));
  }

  // ---- badges
  function buildBadges() {
    var hosts = { wKantoBadges: $('#badges-kanto'), wJohtoBadges: $('#badges-johto') };
    var titles = { wKantoBadges: 'Kanto', wJohtoBadges: 'Johto' };
    Object.keys(hosts).forEach(function (k) { hosts[k].appendChild(el('h3', null, titles[k])); });
    T.badges.forEach(function (b) {
      var host = hosts[b.byte];
      if (!host) { return; }
      var lab = el('label');
      var cb = el('input');
      cb.type = 'checkbox';
      cb.checked = !!((sav[off(b.byte)] >> b.bit) & 1);
      cb.addEventListener('change', function () {
        var o = off(b.byte), m = 1 << b.bit;
        if (cb.checked) { sav[o] |= m; } else { sav[o] &= ~m & 0xff; }
        markDirty();
      });
      lab.appendChild(cb);
      lab.appendChild(el('span', null, b.label));
      host.appendChild(lab);
    });
  }

  // ---- money and names
  function buildMoney() {
    var money = $('#f-money');
    money.value = rdBE('wMoney', 3);
    money.addEventListener('change', function () {
      var v = clamp(+money.value, 0, 999999);
      money.value = v;
      wrBE('wMoney', 3, v);
      markDirty();
    });

    var coins = $('#f-coins');
    coins.value = rdBE('wCoins', 2);
    coins.addEventListener('change', function () {
      var v = clamp(+coins.value, 0, 9999);
      coins.value = v;
      wrBE('wCoins', 2, v);
      markDirty();
    });

    var maxName = T.limits.playerNameLength - 1;
    $('#name-note').textContent = 'Up to ' + maxName +
      ' characters, encoded with the game’s own character map; anything it has no glyph for is dropped.';
    [['#f-player', 'wPlayerName'], ['#f-rival', 'wRivalName']].forEach(function (pair) {
      var inp = $(pair[0]), fld = pair[1];
      inp.maxLength = maxName;
      inp.value = decodeName(off(fld), len(fld));
      inp.addEventListener('change', function () {
        if (!nameIsEncodable(inp.value)) { say('Some characters in that name are not in the game’s font; they were dropped.', true); }
        encodeName(inp.value, off(fld), len(fld));
        inp.value = decodeName(off(fld), len(fld));
        markDirty();
      });
    });
  }

  // ---- bag
  function buildBag() {
    var host = $('#pockets');
    host.textContent = '';
    POCKETS.forEach(function (p) {
      var list = T.items.filter(function (it) { return it.pocket === p.id; });
      var box = el('div', 'pocket');
      box.appendChild(el('h3', null, p.label + ' (max ' + T.limits[p.cap] + ')'));
      var rows = el('div');
      box.appendChild(rows);
      var add = el('button', null, '+ Add ' + p.label.toLowerCase().replace(/s$/, ''));
      add.type = 'button';
      add.addEventListener('click', function () {
        if (bag[p.id].length >= T.limits[p.cap]) { say(p.label + ' pocket is full.', true); return; }
        bag[p.id].push({ id: list[0].id, qty: 1 });
        writeBag();
        drawPocket(p, list, rows);
        markDirty();
      });
      box.appendChild(add);
      host.appendChild(box);
      drawPocket(p, list, rows);
    });
    host.appendChild(tmPocket());
  }

  function drawPocket(p, list, rows) {
    rows.textContent = '';
    var opts = optionsHtml(list, null);
    bag[p.id].forEach(function (entry, i) {
      var row = el('div', 'bagrow');
      var sel = el('select');
      sel.innerHTML = opts;
      sel.value = String(entry.id);
      sel.addEventListener('change', function () {
        entry.id = +sel.value;
        writeBag();
        markDirty();
      });
      row.appendChild(sel);
      if (p.entry === 2) {
        var qty = numInput(entry.qty, 1, T.limits.maxItemStack);
        qty.addEventListener('change', function () {
          entry.qty = clamp(+qty.value, 1, T.limits.maxItemStack);
          qty.value = entry.qty;
          writeBag();
          markDirty();
        });
        row.appendChild(qty);
      }
      var del = el('button', null, '✕');
      del.type = 'button';
      del.addEventListener('click', function () {
        bag[p.id].splice(i, 1);
        writeBag();
        drawPocket(p, list, rows);
        markDirty();
      });
      row.appendChild(del);
      rows.appendChild(row);
    });
    if (!bag[p.id].length) { rows.appendChild(el('p', 'note', 'empty')); }
  }

  function tmPocket() {
    var box = el('div', 'pocket');
    box.appendChild(el('h3', null, 'TMs & HMs'));
    var checks = el('div', 'checks scroll');
    T.tms.forEach(function (tm, i) {
      var lab = el('label');
      var isHm = tm.label.indexOf('HM') === 0;
      var cb = el('input');
      cb.type = 'checkbox';
      cb.checked = bag.tm[i] > 0;
      cb.addEventListener('change', function () {
        bag.tm[i] = cb.checked ? (isHm ? 1 : 1) : 0;
        writeBag();
        markDirty();
      });
      lab.appendChild(cb);
      lab.appendChild(el('span', null, tm.label + ' · ' + nameOf(T.moves, tm.move)));
      checks.appendChild(lab);
    });
    box.appendChild(checks);
    return box;
  }

  // ---- event flags
  var MAX_EVENT_ROWS = 400;
  function buildEvents() {
    var host = $('#events'), filter = $('#ev-filter'), onlySet = $('#ev-onlyset');
    function draw() {
      var q = filter.value.trim().toUpperCase();
      var shown = 0, hidden = 0, setCount = 0;
      host.textContent = '';
      var frag = document.createDocumentFragment();
      T.events.forEach(function (ev) {
        var id = ev[0], name = ev[1];
        var on = !!eventGet(id);
        if (on) { setCount++; }
        if (onlySet.checked && !on) { return; }
        if (q && name.indexOf(q) < 0) { return; }
        if (shown >= MAX_EVENT_ROWS) { hidden++; return; }
        shown++;
        var lab = el('label');
        var cb = el('input');
        cb.type = 'checkbox';
        cb.checked = on;
        cb.addEventListener('change', function () { eventSet(id, cb.checked); markDirty(); });
        lab.appendChild(cb);
        lab.appendChild(el('code', null, name));
        frag.appendChild(lab);
      });
      host.appendChild(frag);
      $('#ev-note').textContent = setCount + ' of ' + T.events.length + ' named flags are set (' +
        T.limits.numEvents + ' flags exist; ' + (T.limits.numEvents - T.events.length) + ' are unnamed). ' +
        'Showing ' + shown + (hidden ? ', ' + hidden + ' more hidden - narrow the filter.' : '.');
      if (!shown) { host.appendChild(el('p', 'note', 'nothing matches')); }
    }
    var timer = null;
    filter.addEventListener('input', function () {
      clearTimeout(timer);
      timer = setTimeout(draw, 150);
    });
    onlySet.addEventListener('change', draw);
    draw();
  }

  // ---- presets
  function buildPresets() {
    var host = $('#presets');
    fetch(PRESET_DIR + 'manifest.json', { cache: 'no-store' }).then(function (r) {
      if (!r.ok) { throw new Error('HTTP ' + r.status); }
      return r.json();
    }).then(function (list) {
      host.textContent = '';
      list.forEach(function (p) {
        var box = el('div', 'preset');
        box.appendChild(el('strong', null, p.title));
        box.appendChild(el('span', null, p.description));
        var b = el('button', null, 'Load this preset');
        b.type = 'button';
        b.disabled = !canWrite;
        b.addEventListener('click', function () {
          if (!window.confirm('Replace your save with "' + p.title + '"?\n\nYour current save is kept under "Restore previous save".')) { return; }
          say('Loading ' + p.title + '…');
          fetchBytes(PRESET_DIR + p.sav).then(function (bytes) {
            installSav(bytes, p.title);
          }).catch(function (e) { say('Could not load that preset: ' + e.message, true); });
        });
        box.appendChild(b);
        host.appendChild(box);
      });
      if (!list.length) { host.appendChild(el('p', 'note', 'no presets are installed')); }
    }).catch(function (e) {
      host.textContent = '';
      host.appendChild(el('p', 'note', 'No presets available (' + e.message + ').'));
    });
  }

  // ------------------------------------------------------------- writing ----

  function saveAndGo(bytes, what) {
    var stash = original ? kvPut(backupKey(), { ram: original, date: Date.now(), title: titleKey })
      : Promise.resolve();
    return stash.then(function () {
      return kvPut(batteryKey(), { ram: bytes, date: Date.now(), title: titleKey, saveSig: saveSig(bytes) });
    }).then(function () {
      return kvDel(resumeKey());
    }).then(function () {
      say(what + ' - starting the game…');
      window.location.href = './index.html';
    }).catch(function (e) {
      say('Could not write the save: ' + (e && e.message ? e.message : e), true);
    });
  }

  function installSav(bytes, what) {
    var img = normalizeSram(bytes);
    var keep = sav;
    sav = img;
    var ok = copyOk(T.sav.copies[0]) || copyOk(T.sav.copies[1]);
    if (!ok) {
      sav = keep;
      say('That .sav does not look like a save for this game (neither copy checksums).', true);
      return;
    }
    if (!copyOk(T.sav.copies[0])) {
      // primary is bad, backup is good: promote the backup, like the game does
      var Pp = T.sav.copies[0], B = T.sav.copies[1];
      sav.set(sav.subarray(B.options, B.checkValue2 + 1), Pp.options);
    }
    finalize();
    saveAndGo(sav, what);
  }

  function applyAndPlay() {
    if (!canWrite) { return; }
    writeParty();
    writeBag();
    finalize();
    saveAndGo(sav.slice(0), 'Save written');
  }

  function restorePrevious() {
    kvGet(backupKey()).then(function (entry) {
      if (!entry || !entry.ram || !entry.ram.length) { say('There is no previous save to restore.', true); return; }
      if (!window.confirm('Put the pre-edit save back? Anything you changed since is lost.')) { return; }
      return kvPut(batteryKey(), {
        ram: entry.ram, date: Date.now(), title: titleKey, saveSig: saveSig(new Uint8Array(entry.ram))
      })
        .then(function () { return kvDel(resumeKey()); })
        .then(function () {
          say('Previous save restored - starting the game…');
          window.location.href = './index.html';
        });
    }).catch(function (e) { say('Restore failed: ' + e.message, true); });
  }

  // ---------------------------------------------------------------- boot ----

  function showNoSave(reason) {
    $('#ed').hidden = false;
    var secs = document.querySelectorAll('.sec');
    Array.prototype.forEach.call(secs, function (s, i) {
      // only the last section (presets + files) is usable without a save
      s.hidden = i !== secs.length - 1;
      s.open = !s.hidden;
    });
    say(reason, true);
  }

  function boot() {
    statusEl = $('#status');
    say('Loading tables…');
    Promise.all([
      fetch(TABLES_URL, { cache: 'no-store' }).then(function (r) {
        if (!r.ok) { throw new Error('tables.json -> HTTP ' + r.status); }
        return r.json();
      }),
      loadRom()
    ]).then(function (got) {
      T = got[0];
      rom = got[1];
      P = T.party;
      titleKey = titleKeyOf(rom);
      return sha256(rom);
    }).then(function (digest) {
      romSha = digest;
      canWrite = romSha === T.rom.sha256;
      buildPresets();
      if (!canWrite) {
        showNoSave('This editor was built for ROM ' + T.rom.sha256.slice(0, 12) +
          ' but the loaded ROM is ' + romSha.slice(0, 12) +
          '. The save offsets would be wrong, so editing is disabled. Rebuild the site from the same source as the ROM.');
        return null;
      }
      return kvGet(batteryKey());
    }).then(function (entry) {
      if (!canWrite) { return; }
      if (!entry || !entry.ram || !entry.ram.length) {
        showNoSave('No save found for ' + titleKey + ' in this browser. Play the game once so it writes one, ' +
          'or load a preset / upload a .sav below.');
        return;
      }
      haveSave = true;
      sav = normalizeSram(new Uint8Array(entry.ram));
      original = sav.slice(0);

      var Pp = T.sav.copies[0], B = T.sav.copies[1];
      var okP = copyOk(Pp), okB = copyOk(B);
      if (!okP && !okB) {
        showNoSave('Both copies of that save fail their checksum - the game would call it corrupted, ' +
          'and this editor will not guess. Load a preset or upload a .sav instead.');
        return;
      }
      if (!okP) {
        sav.set(sav.subarray(B.options, B.checkValue2 + 1), Pp.options);
      }

      readParty();
      readBag();
      buildSpawns();
      buildParty();
      buildBadges();
      buildMoney();
      buildBag();
      buildEvents();
      $('#ed').hidden = false;
      $('#btn-restore').disabled = false;
      var when = entry.date ? new Date(entry.date).toLocaleString() : 'unknown date';
      say((okP ? 'Loaded' : 'Loaded the BACKUP copy (the main one was damaged) of') +
        ' the save for ' + titleKey + ', last written ' + when +
        '. Changes are only written when you press Apply.');
    }).catch(function (e) {
      console.error(e);
      say('Could not start the editor: ' + (e && e.message ? e.message : e), true);
    });

    $('#btn-apply').addEventListener('click', applyAndPlay);
    $('#btn-restore').addEventListener('click', restorePrevious);
    $('#btn-download').addEventListener('click', function () {
      if (!sav) { say('There is no save to download.', true); return; }
      writeParty();
      writeBag();
      finalize();
      download(SAV_NAME, sav.slice(0));
      say('Downloaded ' + SAV_NAME + ' (' + sav.length + ' bytes, raw cartridge RAM).');
    });
    $('#btn-upload').addEventListener('click', function () {
      if (!canWrite) { say('Editing is disabled: the ROM does not match this build.', true); return; }
      $('#file-sav').click();
    });
    $('#file-sav').addEventListener('change', function (ev) {
      var f = ev.target.files && ev.target.files[0];
      if (!f) { return; }
      readFile(f).then(function (bytes) {
        if (!window.confirm('Replace your save with ' + f.name + '?')) { return; }
        installSav(bytes, 'Imported ' + f.name);
      }).catch(function (e) { say('Could not read that file: ' + e.message, true); });
      ev.target.value = '';
    });
    window.addEventListener('beforeunload', function (e) {
      if (!dirty) { return; }
      e.preventDefault();
      e.returnValue = '';
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
}());
